# Generated by Django 5.2 on 2026-04-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ('-is_boosted', '-created_at')},
        ),
        migrations.AddField(
            model_name='job',
            name='boost_credits_spent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='is_boosted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='location_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='credits_spent',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='credits_spent',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
