# Generated by Django 5.2 on 2026-04-28 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_alter_job_options_job_boost_credits_spent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletTopUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('package_name', models.CharField(max_length=120)),
                ('naira_amount', models.PositiveIntegerField()),
                ('credits', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('paystack_access_code', models.CharField(blank=True, max_length=120)),
                ('paystack_transaction_id', models.CharField(blank=True, max_length=120)),
                ('fulfilled', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_topups', to='marketplace.profile')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
